CREATE TABLE `mto_users` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created` datetime DEFAULT NULL,
  `email` varchar(128) DEFAULT NULL,
  `last_login` datetime DEFAULT NULL,
  `mobile` varchar(11) DEFAULT NULL,
  `password` varchar(32) DEFAULT NULL,
  `status` int(11) NOT NULL,
  `username` varchar(64) DEFAULT NULL,
  `name` varchar(64) DEFAULT NULL,
  `avatar` varchar(255) DEFAULT '/assets/images/ava/default.png',
  `updated` datetime DEFAULT NULL,
  `gender` int(11) NOT NULL,
  `role_id` int(11) DEFAULT NULL,
  `source` int(11) NOT NULL,
  `active_email` int(11) DEFAULT NULL,
  `comments` int(11) NOT NULL,
  `fans` int(11) NOT NULL,
  `favors` int(11) NOT NULL,
  `follows` int(11) NOT NULL,
  `posts` int(11) NOT NULL,
  `signature` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

create table abw_user(
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  user_name VARCHAR(200) DEFAULT  null COMMENT '用户姓名',
  nick_name VARCHAR(200) DEFAULT  null COMMENT '用户昵称',
  mobie VARCHAR(20) DEFAULT null COMMENT '手机号',
  email VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
  password VARCHAR(100) DEFAULT NULL COMMENT '密码,使用md5加密',
  signature VARCHAR(400) DEFAULT NULL COMMENT '个性签名',
  status VARCHAR(1) DEFAULT '0' COMMENT '用户状态：0-禁用，1-已激活，2-已实名',
  role_id BIGINT(20) DEFAULT null COMMENT '角色ID',
  source_id VARCHAR(40) DEFAULT  NULL COMMENT '注册渠道',
  fans_count BIGINT(20) DEFAULT 0 COMMENT '粉丝(关注)数',
  support_count BIGINT(20) DEFAULT 0 COMMENT '点赞数',
  comment_count BIGINT(20) DEFAULT 0 COMMENT '评论数',
  gender VARCHAR(2) DEFAULT NULL  COMMENT '性别：M-男，F-女',
  last_login_time timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '上一次登陆时间',
  `avatar` varchar(255) DEFAULT '/assets/images/ava/default.png' COMMENT '用户图像',
  `create_by` varchar(64) DEFAULT 'sys' COMMENT '创建人',
  `create_time` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `modify_by` varchar(64) DEFAULT 'sys' COMMENT '修改人',
  `modify_time` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  remark  varchar(200) DEFAULT 'sys' COMMENT '备注',
  PRIMARY KEY (`id`)
)ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE `paycore_cash` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `source_id` varchar(8) NOT NULL COMMENT '请求来源:QJS-侨金所',
  `out_order_no` varchar(64) NOT NULL COMMENT '外部请求号',
  `out_order_time` datetime DEFAULT NULL COMMENT '外部请求时间',
  `pay_no` varchar(32) NOT NULL COMMENT '支付流水号',
  `member_id` varchar(64) DEFAULT NULL COMMENT '会员账户',
  `inst_member_id` varchar(64) DEFAULT NULL COMMENT '融资机构会员id',
  `invest_order_no` varchar(64) DEFAULT NULL COMMENT '投资订单号',
  `sign_id` varchar(64) DEFAULT NULL COMMENT '投资人绑卡标识号',
  `trade_amount` decimal(10,2) DEFAULT NULL COMMENT '交易金额',
  `original_order_no` varchar(64) DEFAULT NULL COMMENT '原兑付还款订单号',
  `pay_channel_order_no` varchar(32) DEFAULT NULL COMMENT '银行流水号',
  `fxio_code` varchar(16) DEFAULT NULL COMMENT '请求网关返回码',
  `fxio_msg` varchar(64) DEFAULT NULL COMMENT '请求网关返回信息',
  `trade_status` varchar(20) DEFAULT NULL COMMENT '交易状态：I 初始化, P 处理中, F 处理失败, S 处理成功',
  `inner_status` varchar(20) DEFAULT NULL COMMENT '内部状态: P_WITHDRAW-FXIO提现处理中,P_WITHDRAW_QUERY-提现状态查询中,F_WITHDRAW-FXIO提现失败,F_TRANSFER-转账失败,F_FROZEN-冻结失败,F_UNFROZEN-解冻失败,F_SETTLEMENT-结算失败',
  `cash_type` varchar(32) DEFAULT NULL COMMENT '兑付类型：cash-正常兑付,cash_retry-兑付重试,recash-复投兑付',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT 'sys' COMMENT '创建人',
  `create_time` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `modify_by` varchar(64) DEFAULT 'sys' COMMENT '修改人',
  `modify_time` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  `principal_amount` decimal(10,2) DEFAULT NULL COMMENT '本金',
  `reward_amount` decimal(10,2) DEFAULT NULL COMMENT '奖励',
  `interest_amount` decimal(10,2) DEFAULT NULL COMMENT '利息',
  `pre_reinvest_order_no` varchar(64) DEFAULT NULL COMMENT '预复投订单号（天鼋生成）',
  `coupon_member_id` varchar(32) DEFAULT NULL COMMENT '发放奖励的营销会员ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `pay_no` (`pay_no`) USING BTREE,
  KEY `out_order_no` (`out_order_no`) USING BTREE,
  KEY `member_id` (`member_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=15402 DEFAULT CHARSET=utf8 COMMENT='支付核心兑付还款表';

